import * as DB from './backend.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={catalogue_view:'Catalogue views',device_view:'Device views',assessment_start:'Assessment starts',whatsapp_click:'WhatsApp clicks',assessment_submitted:'Assessments submitted',buying_enquiry_submitted:'Buying enquiries submitted'};
let generation=0;
export function clearAdmin(){generation++;document.querySelector('#admin-content')?.replaceChildren();}
export async function openAdmin(){
 const el=document.querySelector('#admin-content'),g=++generation,user=DB.state.user?.id;
 const current=()=>g===generation&&DB.state.user?.id===user;
 el.innerHTML='<p role="status">Loading admin dashboard…</p>';
 try{
 const role=await DB.adminRole();if(!current())return;if(!role)throw Error('Admin access is required.');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 el.innerHTML=`<div class="page-title"><div><p class="eyebrow">${role==='super_admin'?'SUPER ADMIN':'ADMIN'}</p><h1>Your business, at a glance.</h1></div></div><form id="report-filters" class="admin-filters"><label>From<input name="from" type="date" value="${today.slice(0,7)}-01" required></label><label>To<input name="to" type="date" value="${today}" required></label><label>Group signups by<select name="period"><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option><option value="year">Year</option></select></label><button class="primary">Update report</button></form><p class="micro">Dates use India time. Weeks start Monday. Maximum range: 10 years.</p><p id="admin-feedback" role="status"></p><div id="admin-report"></div>${role==='super_admin'?'<section class="form-card"><h2>Manage admins</h2><p>Admin: reports and equipment requests. Super admin: also manages permissions. User: customer access only.</p><form id="admin-search" class="admin-filters"><label>Find a user<input name="search" type="search" maxlength="254" placeholder="Name or email"></label><button class="secondary">Search</button></form><div id="admin-users"></div><div class="admin-pagination"><button class="secondary" id="users-prev">Previous</button><span id="users-page"></span><button class="secondary" id="users-next">Next</button></div></section>':''}`;
 const feedback=el.querySelector('#admin-feedback');let reportGeneration=0;
 async function report(){const seq=++reportGeneration,f=new FormData(el.querySelector('#report-filters')),out=el.querySelector('#admin-report');out.innerHTML='<p>Loading report…</p>';try{const r=await DB.adminReport(f.get('from'),f.get('to'),f.get('period'));if(!current()||seq!==reportGeneration)return;feedback.textContent='';const max=Math.max(1,...r.signups.map(x=>Number(x.count)));
 out.innerHTML=`<div class="admin-metrics"><article class="form-card"><p>New users · selected dates</p><strong>${r.new_users}</strong></article><article class="form-card"><p>Total registered users</p><strong>${r.total_users}</strong></article></div><section class="form-card"><h2>New user signups</h2><div class="admin-bars">${r.signups.map(x=>`<div class="admin-bar"><time>${esc(x.period)}</time><span><i style="width:${100*Number(x.count)/max}%"></i></span><b>${x.count}</b></div>`).join('')}</div></section><div class="admin-columns"><section class="form-card"><h2>Most-used actions</h2><p class="micro">Clicks: signed-in customers only, collected from this update onward; staff excluded. Submissions: saved records, including historical records. Click totals are approximate and do not confirm WhatsApp messages.</p>${table(['Action','Count','Users'],r.actions.map(a=>[labels[a.action]||a.action,a.count,a.users]))}</section><section class="form-card"><h2>Most-viewed devices</h2>${r.devices.length?table(['Device','Views'],r.devices.map(d=>[d.device,d.count])):'<p>No device views in this period yet.</p>'}</section></div>${role==='super_admin'?`<section class="form-card"><h2>Recent permission changes</h2><p class="micro">Latest 30 changes across all dates. IDs identify the actor and affected account.</p>${r.audit.length?table(['When','Changed by','User','Change'],r.audit.map(a=>[new Date(a.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}),a.actor_id,a.target_id,a.old_role+' → '+a.new_role])):'<p>No permission changes yet.</p>'}</section>`:''}`;
 }catch(e){if(current()&&seq===reportGeneration){out.replaceChildren();feedback.textContent=e.message;}}}
 el.querySelector('#report-filters').onsubmit=e=>{e.preventDefault();void report();};
 if(role==='super_admin'){
 let offset=0,seq=0;async function users(){const request=++seq,search=new FormData(el.querySelector('#admin-search')).get('search'),out=el.querySelector('#admin-users');out.innerHTML='<p>Loading users…</p>';try{const r=await DB.adminUsers(search,offset);if(!current()||request!==seq)return;
 out.innerHTML=r.users.length?`<div class="admin-table"><table><thead><tr><th>User</th><th>Role</th><th>Change access</th></tr></thead><tbody>${r.users.map(u=>`<tr><td>${esc(u.name||'Unnamed user')}<br><small>${esc(u.email)}</small></td><td>${esc(u.role)}</td><td><form data-user="${u.id}"><select aria-label="Role for ${esc(u.email)}" name="role">${['user','admin','super_admin'].map(v=>`<option value="${v}" ${u.role===v?'selected':''}>${v.replace('_',' ')}</option>`).join('')}</select><button class="secondary">Save</button></form></td></tr>`).join('')}</tbody></table></div>`:'<p>No users found.</p>';
 el.querySelector('#users-page').textContent=`Page ${offset/25+1}`;el.querySelector('#users-prev').disabled=offset===0;el.querySelector('#users-next').disabled=offset+25>=Number(r.users[0]?.total||0);
 out.querySelectorAll('form').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const target=r.users.find(u=>u.id===form.dataset.user),next=new FormData(form).get('role');if(next===target.role)return;if(!confirm(`Change ${target.email} from ${target.role} to ${next}?`))return;const button=form.querySelector('button');button.disabled=true;try{await DB.setAdmin(target.id,next);if(!current())return;if(target.id===user){location.reload();return;}feedback.textContent='Permissions updated.';await users();await report();}catch(e){if(current())feedback.textContent=e.message;}finally{button.disabled=false;}});
 }catch(e){if(current()&&request===seq){out.replaceChildren();feedback.textContent=e.message;}}}
 el.querySelector('#admin-search').onsubmit=e=>{e.preventDefault();offset=0;void users();};el.querySelector('#users-prev').onclick=()=>{offset=Math.max(0,offset-25);void users();};el.querySelector('#users-next').onclick=()=>{offset+=25;void users();};void users();
 }
 await report();
 }catch(e){if(current())el.innerHTML=`<h2>Admin dashboard unavailable</h2><p>${esc(e.message)}</p><p>If setup is pending, run migration 003 and assign your first super admin.</p>`;}
}
function table(head,rows){return `<div class="admin-table"><table><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
